version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
    - "fishbrain/platform-team"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
    - "fishbrain/platform-team"
