name: Lint

on: [push]

jobs:
  linter:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm ci
          npm run lint
